// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace Projekt_BD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229172532_Initial4")]
    partial class Initial4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod_pocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Numer_budynku")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Numer_mieszkania")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Adresy");
                });

            modelBuilder.Entity("backend.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("AdresId");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("backend.Models.Sprzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data_zakupu")
                        .HasColumnType("date");

                    b.Property<int>("Koszt_wypozyczenia")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Rozmiar")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sprzety");
                });

            modelBuilder.Entity("backend.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data_wypoz")
                        .HasColumnType("date");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("Okres_wypoz")
                        .HasColumnType("int");

                    b.Property<int>("SprzetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("SprzetId");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("backend.Models.Klient", b =>
                {
                    b.HasOne("backend.Models.Adres", "Adres")
                        .WithMany("Klienci")
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("backend.Models.Wypozyczenie", b =>
                {
                    b.HasOne("backend.Models.Klient", "Klient")
                        .WithMany("Wypozyczenie")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Sprzet", "Sprzet")
                        .WithMany("Wypozyczenie")
                        .HasForeignKey("SprzetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Sprzet");
                });

            modelBuilder.Entity("backend.Models.Adres", b =>
                {
                    b.Navigation("Klienci");
                });

            modelBuilder.Entity("backend.Models.Klient", b =>
                {
                    b.Navigation("Wypozyczenie");
                });

            modelBuilder.Entity("backend.Models.Sprzet", b =>
                {
                    b.Navigation("Wypozyczenie");
                });
#pragma warning restore 612, 618
        }
    }
}
